spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://172.19.32.1:5432/postgres
    username: postgres
    password: pg1234

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

constants:
  limit: 200
  message:
    accept: transaction is accepted
    reject: transaction is rejected
    fail: transaction is failed
